scrumble:
  props:
    -
      word: fragen
      meaning: Auskunft, Erklärung o. Ä. erwarten
    -
      word: antwort
      meaning: mündliche oder schriftliche Erwiderung, Entgegnung
    -
      word: fahrrad
      meaning: zweirädriges Fahrzeug
    -
      word: apfel
      meaning: rundliche, festfleischige, aromatisch schmeckende Frucht mit Kerngehäuse